version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: reporting_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/reporting_db?sslmode=disable
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-secret-key
      WHITEBOARD_API_KEY: wb_key_123
      NOTEBOOK_API_KEY: nb_key_456
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: